### PR TITLE
defusedxml check

### PR DESCRIPTION
**Pull request by sbilge**
- Import check for defusedxml is added

### CODE REVIEW

**Review by lkuchenb — COMMENTED** [review]
Why can't we just add a simple import to one of our modules, for example the one that loads openpyxl?
```python
try:
    import defusedxml
except ModuleNotFoundError as err:
    raise RuntimeError("The 'defusedxml' package must be present to safely run ghga-transpiler.") from err
```

**Comment by sbilge** [comment]
Doesn't it make the purpose of the import clearer? Otherwise, it will be just an orphan import.

**Comment by lkuchenb** [comment]
I don't see the harm in the import, also it actually checks if the module can be imported successfully rather than whether it can be found.

Either way, I also checked in the openpyxl source code how they check availability, they also run an import

https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/xml/__init__.py#L29-L35

and it turns out that openpyxl usage can be turned on and off through an environment variable even if it's installed. They export the result in variable `DEFUSEDXML`

https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/xml/__init__.py#L42

so we should not do our own check but just import that variable and check its value! You can import it directly from the root package as it is also imported there

https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/__init__.py#L6

**Review by lkuchenb — CHANGES_REQUESTED** [review]
We need to check the `DEFUSEDXML` value instead of conducting a custom module search.

**Review by lkuchenb — CHANGES_REQUESTED** [review]
* I would suggest to do the import, check and raise at the highest possible level, maybe even the `ghga_transpiler` package (`__init__.py`). We want to be sure every code in our package that uses `openpyxl` passes through this check first. If we embed the check in a specific function of ours, we might write another function later that also uses `openpyxl`. Also like this it's guaranteed the check happens only once.
* What's the reason behind re-introducing the `defusedxml` version constrains?

**Comment by sbilge** [comment]
> * What's the reason behind re-introducing the `defusedxml` version constrains?

The version we used is 0.7 (I did not test the earlier releases on the transpiler). The releases up to and including 0.9.* must be backward compatible. But I am not sure if version 1.* will be. That is why I reintroduced the version constraints for `defusedxml`.

**Comment by lkuchenb** [comment]
You're right, my bad. I forgot that openpyxl does not have a dependency on defusedxml.

**Review by lkuchenb — APPROVED** [review]
Thanks 👍

**Pull request merged**
